### PR TITLE
Added Tower of Hanoi stack implementation

### PR DESCRIPTION
**Pull request by Avninder99**

### CODE REVIEW

**Review by thepranaygupta — CHANGES_REQUESTED** [review]
please add this file to its respective directory.
you can add this in [`Leetcode questions`](https://github.com/thepranaygupta/Data-Structures-and-Algorithms/tree/main/01.%20DataStructures/02.%20Stack/LeetCode%20Questions)

**Comment by Avninder99** [comment]
@thepranaygupta ok sure

**Comment by Avninder99** [comment]
@thepranaygupta I have made the changes.

**Review by thepranaygupta — APPROVED** [review]
Amazing work!! 🥇
Thanks for contributing. 👍

**Pull request merged**
