### PR TITLE
queue using stack C++

### PR DESCRIPTION
**Pull request by rustzz-27**
Pls review my pr

### CODE REVIEW

**Comment by rustzz-27** [comment]
@thepranaygupta pls review my pr
#48

**Review by thepranaygupta — CHANGES_REQUESTED** [review]
please add these files [`here`](https://github.com/thepranaygupta/Data-Structures-and-Algorithms/tree/main/01.%20DataStructures/03.%20Queue/Basic%20Operations/03.%20Queue%20using%20Stacks)

**Comment by rustzz-27** [comment]
H

> please add these files [`here`](https://github.com/thepranaygupta/Data-Structures-and-Algorithms/tree/main/01.%20DataStructures/03.%20Queue/Basic%20Operations/03.%20Queue%20using%20Stacks)

Done pls check

**Comment by rustzz-27** [comment]
@thepranaygupta pls check I have made the changes as suggested

**Comment by rustzz-27** [comment]
@thepranaygupta

**Review by thepranaygupta — APPROVED** [review]

**Pull request merged**
