### PR TITLE
finding height of binary tree added

### PR DESCRIPTION
**Pull request by anandhu720**
Added the method of finding height of binary tree in recursive as well as iterative way with time and space complexity
**Pull request for HackOctober 2021**

### CODE REVIEW

**Review by thepranaygupta — CHANGES_REQUESTED** [review]
please create a new folder named `Tree operations` and another subfolder inside it named `Height of Tree` , then add separate files (README  and C++ code) inside it.

**Comment by anandhu720** [comment]
ok

**Comment by anandhu720** [comment]
@thepranaygupta Made changes

**Comment by thepranaygupta** [comment]
> 
> 
> @thepranaygupta Made changes

Thanks for contributing 😄

**Pull request merged**
